export type { IHomeAnimeData } from './home'
export type { IGenreAnimeData } from './genre'
export type { ISearchFilterAnimeData, ISearchFilterAnimeParams, ISearchSuggestionAnimeData } from './search'
export type { IDetailsAnimeData } from './details'
export type { IScheduleAnimeData } from './schedule'
export type { ICategoryAnimeData } from './category'
export type { IEpisodesAnimeData, IEpisodeAnimeServersData, IEpisodeAnimeStreamingLinksData } from './episodes'
